version: '3' 
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    networks:
      - app-network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - app-network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - WP_DB_NAME=${WP_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_URL=${WP_URL}
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - app-network
    volumes:
      - /home/dlaidet/data/mariadb:/docker-entrypoint-initdb.d/
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - WP_DB_NAME=${WP_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always

networks:
  app-network:
    driver: bridge
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dlaidet/data/wordpress
      o: bind
